### ISSUE TITLE
Corner Radius of tab view

### ISSUE THREAD

**Issue by KevinAnass** [jsuarezruiz/Xamarin.Forms.TabView#13]
how i can add corner radius for left and right

**Comment by AswinPG** [comment]
You can use the TabStripBackgroundView property to give it any background you like. In your case you can place a boxview and give it corner radius.

**Comment by jsuarezruiz** [comment]
@AswinPG Thanks for the answer. Right, you can use `TabStripBackgroundView` property. There is an example in the Gallery using it.
