### ISSUE TITLE
PerformanceTestGallery, scrolling list when swipe between tabs on iOS

### ISSUE THREAD

**Issue by AlexeyBuryanov** [jsuarezruiz/Xamarin.Forms.TabView#4]
[iOS] When you swipe between tabs content in the CollectionView continue to scroll. It's normal? This does not happen on android but iOS...

![1](https://user-images.githubusercontent.com/18596167/88042440-9a060a80-cb54-11ea-8d7f-24bbc2048bb5.gif)

**Comment by jsuarezruiz** [comment]
Thanks for the feedback. The issue has also been fixed.
