### ISSUE TITLE
Nested Tabs Gallery TabIndicator dosen't display properly when upgrading to Xamarin.Forms 4.8

### ISSUE THREAD

**Issue by MadSam08** [jsuarezruiz/Xamarin.Forms.TabView#5]
Hello @jsuarezruiz  I'm using your TabView for and internal project and will be in a great help if this issue could be fixed, beucase we want to use some of the new fetures that xamarin.forms 4.8 provides, but this bug with nested tabs dose't allow us to do the upgrade, I have tried to look into the issue but couldn't figure out what was causing it.
![image](https://user-images.githubusercontent.com/42069882/92362254-61b48e80-f0f8-11ea-9021-569f96c79fe2.png)
![image](https://user-images.githubusercontent.com/42069882/92363643-7a25a880-f0fa-11ea-8a8b-a5c2298eea07.png)

**Comment by jsuarezruiz** [comment]
Thanks for the feedback. The project have been updated to the latest Xamarin.Forms version and the issue has also been fixed.

**Comment by MadSam08** [comment]
> Thanks for the feedback. The project have been updated to the latest Xamarin.Forms version and the issue has also been fixed.

Thanks alot for doing the fix,
